### ISSUE TITLE
use `Unitful.ustrip`

### ISSUE THREAD

**Issue by goretkin** [jw3126/UnitfulRecipes.jl#1]
The definition at https://github.com/jw3126/UnitfulRecipes.jl/blob/5a720a96a380dfe21b9ac1b80d4667997d4b5845/src/UnitfulRecipes.jl#L16
```julia
function stripunit(x, u)
    uconvert.(NoUnits, x/u)
end
```

seems to be the same as what `Unitful.ustrip` accomplishes. I had the same kind of helper in my code because I couldn't find `ustrip`, so I'm bringing it up just in case!

**Comment by jw3126** [comment]
Thanks!

**Comment by jw3126** [comment]
Fixed!
