### ISSUE TITLE
histogram wrong labelled axis

### ISSUE THREAD

**Issue by briochemc** [jw3126/UnitfulRecipes.jl#19]
```julia
using Unitful, UnitfulRecipes, Plots
x = randn(100)*u"m"
histogram(x)
```

gives

![test](https://user-images.githubusercontent.com/4486578/73222643-d9f8c000-41b7-11ea-847b-8e00e015f62e.png)

but the unit should be on the x-axis. I guess it's because in the recipe `plot(x)` assigns the label to the y-axis automatically.

**Comment by jw3126** [comment]
Oh I did not know that. I guess we need to take a loog at the seriestype here: https://github.com/jw3126/UnitfulRecipes.jl/blob/master/src/UnitfulRecipes.jl#L17

**Comment by briochemc** [comment]
> Oh I did not know that. I guess we need to take a loog at the seriestype here: https://github.com/jw3126/UnitfulRecipes.jl/blob/master/src/UnitfulRecipes.jl#L17

Yep I think so too. But maybe there is a smarter way to deal with it? It would be great to be able to infer which axis (and thus which attribute) the data corresponds to... But I'm still not there yet in terms of understanding how all this works 😅

**Comment by briochemc** [comment]
I think https://github.com/jw3126/UnitfulRecipes.jl/commit/1ffc4b6c9ed00c7e8f8657737c9c7f54fa94e882 is a minimal but good (temporary?) fix 😄 

Example output from MWE above:

![fixed_histogram](https://user-images.githubusercontent.com/4486578/75193652-83759780-570b-11ea-91a0-4d9f82cd9308.png)

**Comment by briochemc** [comment]
Actually I introduced a (bug) by assuming the `:seriestype` existed, but now with https://github.com/jw3126/UnitfulRecipes.jl/commit/4456579577458d80bb82c59c23ec195e7f06b07d it should be fine (tested locally this time!)

**Comment by briochemc** [comment]
I will close now but someone might reopen if something is wrong!
