### ISSUE TITLE
Move all the CI stuff from Travis to Github actions?

### ISSUE THREAD

**Issue by briochemc** [jw3126/UnitfulRecipes.jl#22]
This is just a suggestion. 

I suggest this because Plots currently fails to build in Travis Windows CI (which fails the whole CI) and this would also allow us to have OS-specific badges of tests like I just did for [DualMatrixTools.jl](https://github.com/briochemc/DualMatrixTools.jl).

We could more or less copy-paste the workflows from that repo, but you would have to add a few things in the repo's settings:
- add the `CODECOV_TOKEN` in the repo's secret tokens (find it in your codecov)
- add the private `DOCUMENTER_KEY` to the secrets and the public `documenter` key to the "deploy keys" (keys to be generated using DocumenterTools as per [Documenter's documentation](https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#travis-ssh-1))

**Comment by jw3126** [comment]
Would solve the windows CI fail or just give a way to have a badge for it?

**Comment by briochemc** [comment]
Yes, it should solve the Plots issue on windows CI. (And the specific badges are just a gadget bonus IMHO.) 

I also had the same problem with [AIBECS.jl](https://github.com/briochemc/AIBECS.jl) (Plots.jl failing to build on Travis windows CI) and solved it similarly.

**Comment by jw3126** [comment]
Done!

**Comment by briochemc** [comment]
Done with https://github.com/jw3126/UnitfulRecipes.jl/pull/25
