### ISSUE TITLE
Use traits to dispatch

### ISSUE THREAD

**Issue by briochemc** [jw3126/UnitfulRecipes.jl#23]
I think we could have a bit of cleaner way to dispatch on unitful arrays by using traits instead of just dispatch. I had been thinking about this for a while and an answer on slack motivated me to think about this a bit more. This issue is just to start a discussion and keep track of this slack message from Mason Protter (because slack deletes everything): 
```julia
struct Foo         end
struct Contains{T} end
struct Not{T}      end 
f(args...) = f(check_for_foo(args), args...)
check_for_foo(::T) where {T <: Tuple} = Foo ∈ T.parameters ? Contains{Foo}() : Not{Contains{Foo}}()
f(::Contains{Foo}, args...)      = "Foo in $(args)"
f(::Not{Contains{Foo}}, args...) = "Foo not in $(args)"
```
and then
```julia
julia> f(1, 2, 3)
"Foo not in (1, 2, 3)"
julia> f(1, Foo(), 4)
"Foo in (1, Foo(), 4)"
```
This requires some boiler-plate to set up, but it's at least O(1) methods instead of O(2^N)

**Comment by jw3126** [comment]
What are you trying to do? Replace all these?

https://github.com/jw3126/UnitfulRecipes.jl/blob/895451db8b920f45b2b280aa1a08d1c2c46d15b5/src/UnitfulRecipes.jl#L158-L179

That would be cool. If so I guess your suggestion involves touching Plots.jl / the recipe system?

**Comment by briochemc** [comment]
Yes! I am trying but failing so far... 😅 But maybe with some help we'll get to this 😄

**Comment by briochemc** [comment]
For the record this is what I have replaced those lines with:
```julia
#traits
struct HasUnits end
struct HasNoUnits end
unitfultrait(::T) where {T<:Tuple} = any(t <: Quantity for t in eltype.(T.parameters)) ? HasUnits() : HasNoUnits()

# dispatch using traits
(RecipesBase.RecipesBase).apply_recipe(attr::AbstractDict{Symbol, Any}, arrs::Array...) = (RecipesBase.RecipesBase).apply_recipe(attr, unitfultrait(arrs), arrs...)

# Apply the recipe if has units
function (RecipesBase.RecipesBase).apply_recipe(attr::AbstractDict{Symbol, Any}, ::HasUnits, arrs::Array...)
    series_list = RecipesBase.RecipeData[]
    func_return = begin
        println("unitful traitrecipe")
        #recipe!(attr, arrs...) # <- This line is uncommented in UnitfulRecipes
        ([ustrip.(arr) for arr in arrs]...,)
    end
    if func_return != nothing
        push!(series_list, RecipesBase.RecipeData(attr, RecipesBase.wrap_tuple(func_return)))
    end
    @show series_list
    series_list
end
#don't apply it otherwise
function (RecipesBase.RecipesBase).apply_recipe(attr::AbstractDict{Symbol, Any}, ::HasNoUnits, arrs::Array...)
    series_list = RecipesBase.RecipeData[]
    func_return = begin
        print("should be called once only")
        arrs
    end
    push!(series_list, RecipesBase.RecipeData(attr, RecipesBase.wrap_tuple(arrs)))
    @show series_list
    series_list
end
```
but this fails and enters endless loops, so needs fixing :)

**Comment by briochemc** [comment]
Also, Simon Christ mentioned this relevant PR: https://github.com/JuliaPlots/Plots.jl/pull/2503

**Comment by jw3126** [comment]
I guess https://github.com/jw3126/UnitfulRecipes.jl/pull/25 resolves this issue?

**Comment by briochemc** [comment]
Well, I think indirectly it does... sort of :) In the sense that if the point here was to make the code cleaner then I think https://github.com/jw3126/UnitfulRecipes.jl/pull/25 achieves that

**Comment by briochemc** [comment]
Either way, I don't think I'll work on this traits approach any time soon, so I'll close this 🙂 and we can always reopen in the future in case.
