### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by jw3126** [jw3126/UnitfulRecipes.jl#31]
@briochemc I think this package is pretty stable and we can do an 1.0 release. What do you think?

**Comment by briochemc** [comment]
Yes, I agree!

**Comment by jw3126** [comment]
# [ANN] UnitfulRecipes.jl 1.0
@briochemc and myself are happy to announce [UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) 1.0.

[UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) provides recipes for plotting figures ([Plots.jl](https://github.com/JuliaPlots/Plots.jl)) when using data with units ([Unitful.jl](https://github.com/PainterQubits/Unitful.jl)).

```julia
using Unitful, UnitfulRecipes, Plots
const a = 1u"m/s^2"
v(t) = a * t
x(t) = a/2 * t^2
t = (0:0.01:100)*u"s"
plot(x.(t), v.(t), xlabel="position", ylabel="speed")
```

should give something like

![UnitfulRecipeExample](https://user-images.githubusercontent.com/4486578/78975352-451b2700-7b57-11ea-8e7d-42c2860da51f.png)

[UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) also interoperates well with the wider ecosystem:

```julia
using Plots, UnitfulRecipes, Unitful, UnitfulMoles, Measurements
x = collect(-10:2:30) * u"°C"
y = (50 .+ 10atan.(ustrip.(x)/10) .± 3rand.(length(x))) * u"molC/molP"
plot(x, y, ylabel="Organic matter C:P", xlabel="Water temperature", label="")
```
![image](https://user-images.githubusercontent.com/7261506/90950708-ad0e4200-e454-11ea-8494-89585b785708.png)


Head over to the [documentation](https://jw3126.github.io/UnitfulRecipes.jl/stable/) for more examples!

**Comment by jw3126** [comment]
Does that sound good for a discourse announcement @briochemc ?

**Comment by briochemc** [comment]
Yes, of course! Maybe give this example too to say that it also combines well with the recently released UnitfulMoles.jl and other packages like Measurments.jl?

```julia
using Plots, UnitfulRecipes, Unitful, UnitfulMoles, Measurements
x = collect(-10:2:30) * u"°C"
y = (50 .+ 10atan.(ustrip.(x)/10) .± 3rand.(length(x))) * u"molC/molP"
plot(x, y, ylabel="Organic matter C:P", xlabel="Water temperature", label="")
```

should give something like

<img width="712" alt="Screen Shot 2020-08-22 at 4 03 07 pm" src="https://user-images.githubusercontent.com/4486578/90949998-009e8100-e491-11ea-97cf-15c4e065bd62.png">

**Comment by jw3126** [comment]
I edited my post, see above.

**Comment by jw3126** [comment]
https://discourse.julialang.org/t/ann-unitfulrecipes-jl-1-0/45365
