### ISSUE TITLE
Allow plotting functions with unitful x values?

### ISSUE THREAD

**Issue by rafaqz** [jw3126/UnitfulRecipes.jl#5]
It would be nice if `plot(x -> f(x), xs)` worked with unitful xs.

**Comment by jw3126** [comment]
I think this is straight forward to implement. Just add here 
https://github.com/jw3126/UnitfulRecipes.jl/blob/master/src/UnitfulRecipes.jl#L57
something like
```julia
@recipe plot(f::Function, xs::Q) = recipe!(plotattributes, xs, f.(xs))
```

**Comment by rafaqz** [comment]
It would be good if functors worked as well. Would this be acceptable for dispatch?

```julia
@recipe plot(f, xs::Q) = recipe!(plotattributes, xs, f.(xs))
```

**Comment by jw3126** [comment]
I think it is probably fine if only `UnitfulRecipes` is used. If however, another package defines say `@recipe plot(s::MyStruct, xs::AbstracrVector)` we are in trouble. But yeah, if you provide a PR I am fine with either variant.

**Comment by rafaqz** [comment]
Yeah. Maybe `Function` is the best we can practically do. PR on the way.

**Comment by jw3126** [comment]
#7
