### ISSUE TITLE
Shape() fails on conversion

### ISSUE THREAD

**Issue by DanDeepPhase** [jw3126/UnitfulRecipes.jl#53]
The Shape() function gives the `ERROR: DimensionError:  and m are not dimensionally compatible.`

```julia
using Unitful, Plots, UnitfulRecipes
Shape([(1u"m",1u"m"),(2u"m",2u"m"),(1u"m",2u"m")])
```

**Comment by gustaphe** [comment]
`Shape` doesn't hook into the recipes system at all (and indeed only has arguments `::Vector{Float64}`). If `Plots.jl` had 

```julia
struct Shape{X, Y} where {X<:Number, Y<:Number}
x::Vector{X}
y::Vector{Y}
end
```

then this would be fairly easy to implement. As is I don't think it's worth it. Is there a reason you don't want `plot([(1u"m",1u"m"),(2u"m",2u"m"),(1u"m",2u"m")]; st=:shape)`?

**Comment by gustaphe** [comment]
I've made a PR to Plots that would solve this.

**Comment by DanDeepPhase** [comment]
Thanks! 
I didn't use `st=:shape` because i didn't understand that usage. I thought i had to use the Shape function, and that the seriestype was only for line styles like dashes and dots. 
`st=:shape` solves my current workflow, but perhaps the PR can help others from getting stuck

**Comment by briochemc** [comment]
I guess this can be closed then?
