### ISSUE TITLE
Support Unitful xticks and yticks?

### ISSUE THREAD

**Issue by JeffFessler** [jw3126/UnitfulRecipes.jl#55]
Thanks for this great package.  Currently it supports Unitful `xlim` very nicely, but Unitful `xticks` leads to an error.  This caught me because I often use `xticks=[x[1],x[end]]` to streamline plots and it fails if x has units.  My workaround is `xticks=[x[1],x[end]] / oneunit(x[1])` which is fine for now but I wanted to report the issue because it seems like it would be nicely consistent to support having the ticks be specified in the same units as the corresponding axis.

```julia
using Unitful, UnitfulRecipes, Plots 
x = 1u"mm" * (1:30)
scatter(x, 2x) # works as expected
scatter(x, 2x; xlim=(10u"mm", 20u"mm")) # works as expected!
scatter(x, 2x; xlim=(1u"cm", 2u"cm")) # works as expected - yay!
scatter(x, 2x; xticks=[1u"cm", 2u"cm"]) # error message

ERROR: DimensionError: 0.13 and 1.0 cm are not dimensionally compatible.
```

**Comment by jw3126** [comment]
Thanks for reporting. Would be great to support this. Should also be not too hard to implement, we just have to strip the unit from the ticks, just like we to for e.g. the lims:
https://github.com/jw3126/UnitfulRecipes.jl/blob/ca60ab815852d4fc86f931051d532fa6cd2d1d99/src/UnitfulRecipes.jl#L37
You want to give it a stab? A PR would be awesome!
