### ISSUE TITLE
put units in label instead of tick labels

### ISSUE THREAD

**Issue by briochemc** [jw3126/UnitfulRecipes.jl#8]
Currently, this MWE

```julia
using Unitful, UnitfulRecipes, Plots
x = rand(10)*u"m"
y = rand(10)*u"s"
plot(x,y)
```

gives 

![Screen Shot 2020-01-17 at 4 40 56 PM](https://user-images.githubusercontent.com/4486578/72587212-9cd73700-3948-11ea-97b1-f6ee7aeb9f33.png)

IMHO, it's better to show units in the axis label rather than at every tick. My current solution is either

```julia
plot(ustrip(x), ustrip(y), xlabel=string(unit(eltype(x))), ylabel=string(unit(eltype(y))))
```

which gives 

![Screen Shot 2020-01-17 at 4 43 11 PM](https://user-images.githubusercontent.com/4486578/72587280-cb551200-3948-11ea-9ddf-0651bee36d8f.png)

or if I have a name for axis labels already, something like

```julia
plot(ustrip(x), ustrip(y), xlabel="x ($(unit(eltype(x))))", ylabel="y ($(string(unit(eltype(y)))))")
```

which gives

![Screen Shot 2020-01-17 at 4 43 38 PM](https://user-images.githubusercontent.com/4486578/72587295-da3bc480-3948-11ea-8b06-c4bc11ef2b34.png)

Is that at all doable with recipes? If yes I would love this to be implemented instead of the current behavior!

**Comment by asinghvi17** [comment]
Yeah that's doable - just mutate the label.  You can get the value from `plotattributes["xlabel"]`, modify it, then set xlabel := newxlabel.

**Comment by briochemc** [comment]
OK great I think I have a working example, I will make a PR.

Please disreguard the images that come below, I use this issue as a placeholder to add those to the revised readme in the PR as examples...

![example1](https://user-images.githubusercontent.com/4486578/72591885-74a20500-3955-11ea-9552-489451bd01fd.png)
![example2](https://user-images.githubusercontent.com/4486578/72591886-74a20500-3955-11ea-880b-ae34a67fb1ff.png)
![example3](https://user-images.githubusercontent.com/4486578/72591888-74a20500-3955-11ea-9630-344700694002.png)
![example4](https://user-images.githubusercontent.com/4486578/72591890-753a9b80-3955-11ea-8aa3-0b89ea42c6ec.png)

**Comment by briochemc** [comment]
(just using this as a placeholder for more images... PR incoming)

![example5](https://user-images.githubusercontent.com/4486578/72728617-e42c2480-3be1-11ea-8050-6b7d4614798a.png)
![example6](https://user-images.githubusercontent.com/4486578/72728618-e42c2480-3be1-11ea-8581-499a237aa4d5.png)
![example7](https://user-images.githubusercontent.com/4486578/72728619-e4c4bb00-3be1-11ea-8801-113469a3a28a.png)
![example8](https://user-images.githubusercontent.com/4486578/72728620-e4c4bb00-3be1-11ea-91c3-1eddc88491bf.png)
